core/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("url_shortener.urls", namespace="url_shortener"))
]

url_shortener/urls.py
from django.conf.urls import url

from .views import HomeView, URLCreateView, ResultView

urlpatterns = [
    # url(r'^((?P<uuid>[\w-]+)?)$', HomeView.as_view(), name="index"),
    url(r'^result/(?P<unique_code>[\w-]+)$', ResultView.as_view(), name="result"),
    url(r'^create$', URLCreateView.as_view(), name="create"),
    url(r'^((?P<unique_code>[\w-]+)?)$', HomeView.as_view(), name="index"),
    
]


# www.example.com/((?P<uuid>[\w-]+)?)/
# www.example.com/create/
# www.example.com/results/

url_shortener/models.py
import uuid
from django.db import models

# Create your models here.
class URLRedirect(models.Model):
    url = models.URLField(max_length=4096)
    unique_code = models.CharField(max_length=8, unique=True, blank=True)

    def save(self, *args, **kwargs):
        if self.pk is None and self.unique_code in [None, '']:
            self.unique_code = self.uuid_generator()

        super(URLRedirect, self).save(*args, **kwargs)

    def uuid_generator(self):
        unique_code = uuid.uuid4().hex[:8].upper()
        if URLRedirect.objects.filter(unique_code=unique_code).exists():
            self.uuid_generator()
        else:
            return unique_code

url_shortener/forms.py
from django import forms


from .models import URLRedirect


class URLRedirectForm(forms.ModelForm):

    url = forms.URLField(max_length=4096, label='', widget=forms.TextInput(attrs={'placeholder': 'URL'}))

    class Meta:
        model = URLRedirect
        fields = ['url']

    def __init__(self, *args, **kwargs):
        super(URLRedirectForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control input-lg'

url_shortener/views.py
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views.generic import CreateView, TemplateView
from django.views.generic.edit import FormView

from .models import URLRedirect

from .forms import URLRedirectForm


class HomeView(FormView):
	template_name = "index.html"
	form_class = URLRedirectForm

	def dispatch(self, request, *args, **kwargs):
		if self.kwargs.get('unique_code') is not None:
			# If unique code exists and object found in database, redirect user to its original url.
			try:
				url_object = URLRedirect.objects.get(unique_code=self.kwargs.get('unique_code'))
				return HttpResponseRedirect(url_object.url)
			except URLRedirect.DoesNotExist:
			# Redirect to home page if shortened URL does not exist.
				return HttpResponseRedirect("/")
		else:
			return super(HomeView, self).dispatch(request, *args, **kwargs)

	def get_success_url(self):
		return reverse('url_shortener:index')


class URLCreateView(CreateView):
	form_class = URLRedirectForm
	template_name = "index.html"

	def form_valid(self, form):

		url = form.instance.url
		try:
			self.object = URLRedirect.objects.get(url=url)
		except URLRedirect.DoesNotExist:
			return super(URLCreateView, self).form_valid(form)

		return HttpResponseRedirect(self.get_success_url())

	def get_success_url(self):
		return reverse('url_shortener:result', kwargs={'unique_code': self.object.unique_code})


class ResultView(TemplateView):
	template_name = "result.html"

	def get_unique_code(self):
		unique_code = self.kwargs["unique_code"]
		return unique_code


	def get_context_data(self, **kwargs):
		context = super(ResultView, self).get_context_data(**kwargs)
		context["result_url"] = "http://%s/%s" % (get_current_site(self.request), self.get_unique_code())
		return context

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- <link rel="stylesheet" href="style.css" /> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Merriweather">

    <title>URL Shortener</title>
</head>

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">Mark Sia Hansheng</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <li><a>URL Shortener</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

{% block body %}
{% endblock %}

{% block page_js %}
{% endblock %}
</html>

templates/index.html
{% extends 'base.html' %}

{% block body %}
<div class="jumbotron" id="home-banner">
  <div class="container">

  <div class="mt-70"></div>

  <h1 class="text-center banner-title">Paste a link to shorten it.</h1>

  <div class="mt-150"></div>

  <div class="col-md-8 col-md-offset-2">
    <form action="{% url 'url_shortener:create' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Submit" class="btn btn-info btn-block btn-lg" />
    </form>
  </div>
    
  </div>
</div>
{% endblock body %}

templates/result.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
	<h2 style="text-decoration:underline"><a href="/">Back to Home</a></h2>
</div>

<div class="jumbotron" id="home-banner">
  <div class="container">

  <div class="mt-70"></div>

  <h1 class="text-center banner-title">Your shortened link:</h1>
  
  <div class="mt-40"></div>

  <div class="col-md-8 col-md-offset-2 text-center">
  	<h2 id="result">{{ result_url }}</h2>

  	<br><br>

  </div>
  </div>
</div>

{% endblock %}

{% block page_js %}
{% endblock %}